version: '3'
services:
  db:
    image: mysql:8.0
    container_name: local-mysql-fastcampus
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=novinimut
      - MYSQL_DATABASE=fastcampus
    volumes:
      - D:\novin\fastcampus\instance-db:/var/lib/mysql
